### ISSUE TITLE
Mnemonics issue

### ISSUE THREAD

**Issue by markiewb** [ranSprd/netbeans-openedFiles#1]
![2016-04-23_16h04_20](https://cloud.githubusercontent.com/assets/1857095/14761902/4329a1ac-096d-11e6-8125-64eee4e5e03a.png)

**Comment by Chris2011** [comment]
Yes I know the bug, I will have a look soon. I don't know the problem yet, because it will take the right actions as you can see in the code.

**Comment by markiewb** [comment]
@Chris2011: Fixed and more https://github.com/markiewb/netbeans-openedFiles/commit/d02e141d2ffccd758a1eca8ce56b16eb0a1b9411 (unfinished, you can continue)

**Comment by Chris2011** [comment]
Can you please make a pull request, so that we can merge it?

**Comment by markiewb** [comment]
@Chris2011: Give https://github.com/ranSprd/netbeans-openedFiles/issues/2 a try

**Comment by Chris2011** [comment]
I see that after your merge, the reload buttons disappears. Have to figure out what happened to him.

**Comment by Chris2011** [comment]
Still fixed.
